### ISSUE TITLE
0.8.3 causes issue with ordered sets

### ISSUE THREAD

**Issue by bonebox** [3lvis/DATAFilter#14]
Hey @3lvis!

I'm using Sync in a project and have an ordered relationship in my Core Data model.  Previously, Sync had been handling this correctly and the objects were mapped to my Core Data ordered set in the same order they were in the JSON.  After updating to the latest Sync, however, I noticed the objects were no longer in order.  It appears that the issue is with DATAFilter 0.8.3.  After reverting to 0.8.2, it works again as expected.

**Comment by 3lvis** [comment]
Hi @bonebox!

I'll revert the change, sorry for this! Added an issue for adding a unit test for ordered sets. :)

https://github.com/3lvis/DATAFilter/issues/15

**Comment by 3lvis** [comment]
The change has been reverted on 0.8.4, I'll check for another way to do this without breaking ordered sets.

How do you do this in Core Data? Do you use this?

<img width="308" alt="screen shot 2015-08-22 at 09 41 56" src="https://cloud.githubusercontent.com/assets/1088217/9423034/13cf2624-48b2-11e5-8bfb-485619cab5b9.png">

Or is it something else?

**Comment by bonebox** [comment]
Yes, that's exactly what I'm doing.  Represented by an NSOrderedSet.  Thanks!
