### ISSUE TITLE
Migrate tests to Swift in swifty branch

### ISSUE THREAD

**Issue by FrancisBehnen** [3lvis/DATAFilter#25]
As mentioned in https://github.com/3lvis/DATAFilter/pull/24#issuecomment-233619716 it looks like we can't bridge `DATAFilterOperation` so the tests will have to be migrated to Swift (Mirrored in my fork: https://github.com/FrancisBehnen/DATAFilter/issues/1)

**Comment by 3lvis** [comment]
I'm migrating them.

**Comment by 3lvis** [comment]
Done! Two tests are failing, though.

**Comment by 3lvis** [comment]
<img width="250" alt="screen shot 2016-07-19 at 18 38 15" src="https://cloud.githubusercontent.com/assets/1088217/16958241/000dc684-4de0-11e6-9f16-e99b551135a2.png">

**Comment by 3lvis** [comment]
https://github.com/3lvis/DATAFilter/commit/761dd9cfcf3d95556dba0579570edd0686f9349e
